version: '3.8'

services:
  app:
    build: .
    image: overpathz/rendertestbot

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testrenderdb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: testrenderdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/

  redis:
    image: redis

volumes:
  postgres_data:
