spring.application.name=render-test-bot
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
tiny.url.api.key=${TINY_URL_API_KEY}